@startuml
scale 1.3

class Unit{}

class Structure{}

class Bionic{}

class Mechanic{}


class Mineral{
 유닛을생산()??
}


class Terran{}
class Zerg{}
class Protoss{}


class marine{
 공격()
}
class medic{
 공격불가능

 생물유닛치료가능()
}

class Tank{
 공격()
}
class Vulture{
 공격()
}

class Scv{
 매딕치료대상

 공격()
 자원채취()
 기계유닛수리()
}



class Zergling{
생물유닛
매딕에 의해 치료가능

서서희회복()
}
class Hydra{
생물유닛
매딕에 의해 치료가능

서서희회복()
}
class ZergStructure{
 생물유닛
 매딕에 의해 치료불가

서서희회복()
}

class Zealot{
 방어막
 생물유닛

 방어막회복()
 매딕에 의해 치료()
}
class Dragon{
 방어막
 기계유닛

 방어막회복()
}
@enduml