### GET
GET https://jsonplaceholder.typicode.com/posts/1

### POST
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "userId": 100,
  "id": 10,
  "title": "test",
  "body": "test"
}

### 삭제
DELETE https://jsonplaceholder.typicode.com/posts/1

### 일부 수정하면 나머지 필드는 그대로 유지되고 변경을 요청한 필드만 바뀜
PATCH https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
  "userId": 200,
  "title": "수정했으"
}

### 모두 수정해줘야 한다. 누락된 필드는 null로 바뀜
PUT https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
  "userId": 150
}

### 마스크 재고 API 테스트
GET https://gist.githubusercontent.com/junsuk5/2b34223fb2368d2bf44c85082745649a/raw/00cb276cb4f4f9573d868e88382f6f7f6759df31/mask_store.json