@startuml

scale 0.7

'종족 인터페이스
interface race{
 string name
}

'3종족
class Terran implements race{}
class Zerg implements race{}
class Protoss implements race{}

'미네랄자원
class Mineral{
 amount
}

'공격
interface Attackable{
 void attack()
}

'회복
interface Recoverable{
 void recover()
}

'치료 매딕
interface Cureable{
 bool cureable()
}

'수리
interface Repairable{
 bool repairable()
}

'채취
interface mineable{
 void mining()
}

'종족
abstract class Unit{
 Race race
 string unitName

  Identify(Race race)
}

class Bionic extends Unit{}

class Mechanic extends Unit{}

class marine extends Bionic implements Attackable {}
class medic extends Bionic implements Cureable {}

class Tank extends Mechanic implements Attackable, Repairable {}
class Vulture extends Mechanic implements Attackable, Repairable {}

class Scv extends Mechanic implements Attackable, Cureable, mineable, Repairable {}

class Zergling extends Bionic implements Attackable, Recoverable {}
class Hydra extends Bionic implements Attackable, Recoverable {}
class ZergStructure extends Bionic implements Recoverable, Structure {}

class Zealot extends Bionic implements Attackable, Recoverable, Cureable{}
class Dragon extends Mechanic implements Attackable, Recoverable {}

abstract Structure{
 Race race
 string unitName
 void build()
}

@enduml