@startuml
'https://plantuml.com/class-diagram

abstract class asset {
  String name
  int price
}

interface thing {
  {abstract} double get weight
  {abstract} set weight(double weight)
}

abstract class TangibleAsset extends asset implements thing{
  String color
}

abstract class intangbleasset extends asset {
  String patent
}

class Book extends TangibleAsset {
 String color
 String isbn
}

class Computer extends TangibleAsset {
 String color
 String makerName
}

@enduml