@startuml

class Cleric{
   + int hp
   - int mp

   + void attack()
   - void die()
}

interface Attackable{
    {abstract} void attack()
}

interface Attackable{
}

abstract class Character{
    {abstract} void attack(Slime slime)
}

class Hero extends Character implements Attackable{
}

class SuperHero extends Hero{
}



@enduml