@startuml
scale 1
class Cleric {
    ..Static..
    {static} maxHp
    {static} maxMp
    ..PublicData..
    +String name
    +int hp
    +int mp
    ..PrivateData..
    -int _selfAidUseMp
    -int _randomHealRange
    ..Method..
    +void selfAid()
    +int pray(int time)
}

class Hero {
    ..PublicData..
    +String name
    +int hp
    +int heroMaxHp
    ..Method..
    +void attack(Slime slime)
    +void run()
}

class Wizard {
    ..Static..
    {static}wizardDefaultMp
    ..PublicData..
    +int wizardNameLimit
    +int wizardMinMpLimit
    +int healHp
    +int healMpCost
    ..PrivateData..
    -String _name
    -int _hp
    -int _mp
    -Wand? _wand
    ..Getter..
    +String wizardName()
    +int wizardHp()
    +int wizardMp()
    +Wand? wand()
    ..Setter..
    +void wizardName(String value)
    +void wizardHp(int value)
    +void wizardMp(int value)
    +void wand(Wand? value)
    ..Method..
    +void heal(Hero hero)
}

class GreatWizard extends Wizard {
    ..Static..
    {static}int greatWizardDefaultMp
    ..PublicData..
    +int greatWizardHealHp
    +int greatWizardHealMpCost
    +int greatWizardSuperHealMpCost
    ..Method..
    +void heal(Hero hero)
    +void superHeal(Hero hero)
}

class Wand {
    ..PublicData..
    -int wandNameLimit
    -double wandPowerMinValue
    -double wandPowerMaxValue
    ..PrivateData..
    -String _name
    -double _power
    ..Getter..
    +String wandName()
    +double wandPower()
    ..Setter..
    +void wandName(String value)
    +void wandPower((String value)
}

class Person {
    ..PublicData..
    +String name
    +int birthYear
    ..Getter..
    +int age()
    ..Method..
    -void _collectionPractice2()
    -void _collectionPractice3()
}

class Slime {
    ..PublicData..
    +int hp
    +int level
    +String suffix
    ..Method..
    +void run()
    +void attack(Hero hero)
}

class PoisonSlime extends Slime {
    ..PrivateData..
    -int _poisonCount
    -double _poisonDamageRatio
    ..Getter..
    +int poisonCount()
    ..Setter..
    +void poisonCount(int value)
    ..Method..
    +void attack(Hero hero)
}

note right of Hero
    Dart 수업용 Class
end note
note left of Person::_collectionPractice2
    컬렌션 연습문제 2번 출력용 함수
end note
note left of Person::_collectionPractice3
    컬렌션 연습문제 3번 출력용 함수
end note
@enduml