@startuml
'https://plantuml.com/class-diagram
!include starcraft_common.puml

class Zealot extends Protoss implements AttackAble, Bionic, HealAble, Unit
class Dragun extends Protoss implements AttackAble, Mechanic, Unit
@enduml