@startuml
'https://plantuml.com/class-diagram
scale 1.5

class Computer extends TangibleAsset {
}

class Book extends TangibleAsset {
}

abstract class TangibleAsset extends Asset implements Thing
abstract class Asset

abstract class IntangibleAsset extends Asset

class 특허권 extends IntangibleAsset

interface Thing



@enduml